[config]
caching = true
fallback_color = "#4285f4"

[config.wallpaper]
set = false
command = "awww img {{ image }}"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.template"
output_path = "~/.config/kitty/themes/generated.conf"

[templates.fuzzel]
input_path = "~/.config/matugen/templates/fuzzel.template"
output_path = "~/.config/fuzzel/colors.ini"

[templates.eww]
input_path = "~/.config/matugen/templates/eww.template"
output_path = "~/.config/eww/colors.scss"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.template"
output_path = "~/.config/hypr/theme.conf"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock.template"
output_path = "~/.config/hypr/hyprlock-theme.conf"

