set nocompatible
filetype plugin indent on
syntax on

set number
set relativenumber
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set hidden
set showcmd
set incsearch
set hlsearch
set ignorecase
set smartcase
set mouse=a
set clipboard=unnamedplus
set updatetime=300

set undofile

