# basic setting
set -g mouse on
set -g history-limit 10000
setw -g mode-keys vi

# stable term inside tmux
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:Tc"

# theme
set -g status-style bg=default
set -g window-style bg=default
set -g window-active-style bg=default
set -g pane-border-style bg=default
set -g pane-active-border-style bg=default
set -g message-style bg=default
set -g message-command-style bg=default
set -g mode-style bg=default

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux reloaded"
