# Backend
backend = "glx";
vsync = true;
glx-no-stencil = true;
use-damage = true;

# Opacity
active-opacity = 1.0;
inactive-opacity = 0.95;

opacity-rule = [
    "100:class_g = 'i3bar'",
    "95:class_g = 'kitty' && focused",
    "85:class_g = 'kitty' && !focused"
];

# Fading
fading = true;
fade-in-step = 0.04;
fade-out-step = 0.04;
fade-delta = 5;

# Rounded corners
corner-radius = 8;

# Shadow
shadow = true;
shadow-radius = 8;
shadow-offset-x = -4;
shadow-offset-y = -4;
shadow-opacity = 0.25;
shadow-exclude = [
    "class_g = 'i3-frame'",
    "_GTK_FRAME_EXTENTS@:c"
];
