########################
# Environment sync
########################

# exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd --all

########################
# Portal (needed for many apps)
########################

exec-once = /usr/lib/xdg-desktop-portal-hyprland

########################
# Notifications
########################

exec-once = mako

########################
# Wallpaper daemon
########################

exec-once = awww-daemon

########################
# EWW widgets
########################

exec-once = sh -c 'pkill eww || true; eww daemon; sleep 1; eww open bar'
#exec-once = pkill eww || true
#exec-once = eww daemon
#exec-once = eww open bar
