########################
# Notifications
########################

exec-once = uwsm app -- mako

########################
# Wallpaper daemon
########################

exec-once = uwsm app -- awww-daemon

########################
# EWW widgets
########################

exec-once = uwsm app -- sh -c 'pkill eww || true; eww daemon; sleep 1; eww open bar'
