-- Main entry: only requires + base look.
-- Each require() is its own lua scope, so an error in one file does not stop the others.

require("env")
require("monitors")
require("input")
require("animations")
require("rules")
require("keybinds")
require("autostart")

-- Basic look
hl.config({
  general = {
    gaps_in = 6,
    gaps_out = 10,
    border_size = 2,
    layout = "dwindle",
  },

  dwindle = {
    preserve_split = true,
  },

  decoration = {
    rounding = 10,
    blur = {
      enabled = true,
      size = 6,
      passes = 2,
    },
  },

  misc = {
    disable_hyprland_logo = true,
    disable_splash_rendering = true,
  },
})

-- Colors generated by matugen. Absent on a fresh checkout until a wallpaper is
-- applied, and require() on a missing module is fatal — hence pcall.
pcall(require, "theme")
