$lock_bg = rgb(121318)
$lock_fg = rgb(e3e1e9)
$lock_primary = rgb(b9c3ff)
$lock_on_primary = rgb(212c61)
$lock_surface_variant = rgb(46464f)
$lock_surface_container = rgb(1f1f25)
$lock_outline = rgb(90909a)
$lock_outline_variant = rgb(46464f)
$lock_error = rgb(ffb4ab)
$lock_tertiary = rgb(e5bad8)
$lock_dim = rgba(e3e1e988)
