$lock_bg = rgb(111318)
$lock_fg = rgb(e1e2e9)
$lock_primary = rgb(a5c8ff)
$lock_on_primary = rgb(00315e)
$lock_surface_variant = rgb(43474e)
$lock_surface_container = rgb(1d2024)
$lock_outline = rgb(8d9199)
$lock_outline_variant = rgb(43474e)
$lock_error = rgb(ffb4ab)
$lock_tertiary = rgb(dabde2)
$lock_dim = rgba(e1e2e988)
