# Font
font_family			FiraCode Nerd Font
font_size			11.0

# Behavior
enable_audio_bell		no
confirm_os_window_close		0

# Window padding
window_padding_width		4

# general theme
background_opacity 0.80
dynamic_background_opacity yes

# TERM
term				xterm-256color

# Optional includes
include keybinds.conf
include themes/generated.conf
